version: '3'
services:

  db:
    image: mongo:4.0.23
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"

  webserver:
    image: nginx:stable
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8081:80"
    environment:
      - NGINX_PORT=80

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web_app
    restart: always
    volumes:
      - ./src:/app:delegated
    ports:
      - "4000:4000"
      - "3000:3000"
      - "3035:3035"
      - "9000:9000"
      - "3001:3001"
    depends_on:
      - db
      - webserver
